# Generated by Django 5.1 on 2024-08-11 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresarios', '0006_alter_empresas_logo_propostainvestimento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropostaInvestimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor da proposta')),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentual da proposta')),
                ('status', models.CharField(choices=[('AS', 'Aguardando assinatura'), ('PE', 'Proposta enviada'), ('PA', 'Proposta aceita'), ('PR', 'Proposta recusada')], default='AS', max_length=2, verbose_name='Status')),
                ('selfie', models.FileField(blank=True, null=True, upload_to='selfies/', verbose_name='Selfie')),
                ('rg', models.FileField(blank=True, null=True, upload_to='rgs/', verbose_name='RG')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='propostas_investidores', to='empresarios.empresas', verbose_name='Empresa')),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='propostas_investidores', to=settings.AUTH_USER_MODEL, verbose_name='Investidor')),
            ],
            options={
                'verbose_name': 'Proposta de Investimento',
                'verbose_name_plural': 'Propostas de Investimento',
            },
        ),
    ]
