# Generated by Django 5.1 on 2024-08-11 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresarios', '0007_delete_propostainvestimento'),
        ('investidores', '0003_alter_propostainvestimento_percentual_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='propostainvestimento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empresarios.empresas'),
        ),
        migrations.AlterField(
            model_name='propostainvestimento',
            name='investidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propostainvestimento',
            name='percentual',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='propostainvestimento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
