# Generated by Django 5.1 on 2024-08-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investidores', '0004_alter_propostainvestimento_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propostainvestimento',
            name='percentual',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
