# Generated by Django 5.1 on 2024-08-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='cnpj',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='estagio',
            field=models.CharField(choices=[('I', 'Tenho apenas uma ideia'), ('MVP', 'Possuo um MVP'), ('MVPP', 'Possuo um MVP com clientes pagantes'), ('E', 'Empresa pronta para escalar')], default='I', max_length=4),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='percentual_equity',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='pitch',
            field=models.FileField(upload_to='pitches/'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='publico_alvo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
