# Generated by Django 5.1 on 2024-08-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresarios', '0004_metricas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='logo',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
