# Generated by Django 5.1 on 2024-08-11 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresarios', '0006_alter_empresas_logo_propostainvestimento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropostaInvestimento',
        ),
    ]
